name: flow

on:
  pull_request:
    branches:
      - Production

jobs:
  check-source:
    name: flow
    runs-on: ubuntu-latest
    steps:
      - name: Fail if not from release/* or hotfix/*
        run: |
          echo "🔍 PR Source Branch: ${{ github.head_ref }}"
          
          BRANCH="${{ github.head_ref }}"
          
          if [[ ! "$BRANCH" =~ ^(Release|Hotfix)/ ]]; then
            echo "❌ Only Release/* or Hotfix/* branches can merge into production."
            exit 1
          fi